# Project 4 - Interpreting Data

**Data Preperation**

***Importing and Merging***

In [12]:
#importing all different libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import geopandas as gpd

In [8]:
#creating data sets
all_tracts = pd.read_csv("NRI_Table_CensusTracts.csv")
indi_nri = all_tracts[all_tracts["STATE"] == "Indiana"]
indi_svi = pd.read_csv("Indiana.csv")

kan_nri = all_tracts[all_tracts["STATE"] == "Kansas"]
kan_svi = pd.read_csv("Kansas.csv")

In [7]:
kan_nri.head(1)

,OID_,NRI_ID,STATE,STATEABBRV,STATEFIPS,COUNTY,COUNTYTYPE,COUNTYFIPS,STCOFIPS,TRACT,...,WNTW_EALS,WNTW_EALR,WNTW_ALRB,WNTW_ALRP,WNTW_ALRA,WNTW_ALR_NPCTL,WNTW_RISKV,WNTW_RISKS,WNTW_RISKR,NRI_VER
29866,30746,T20001952600,Kansas,KS,20,Allen,County,1,20001,952600,...,90.67641,Relatively High,0.000013,4.104483e-07,9.270264e-07,83.120337,21079.537153,92.02307,Relatively High,December 2025

In [10]:
#merging data sets
kan_nri['STCNTY'] = kan_nri['STCOFIPS']
indi_nri['STCNTY'] = indi_nri['STCOFIPS']

kan_data = pd.merge(kan_nri, kan_svi, on = 'STCNTY')
indi_data = pd.merge(indi_nri, indi_svi, on = 'STCNTY')

C:\Users\sevic\AppData\Local\Temp\ipykernel_8716\2345094257.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  kan_nri['STCNTY'] = kan_nri['STCOFIPS']
C:\Users\sevic\AppData\Local\Temp\ipykernel_8716\2345094257.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  indi_nri['STCNTY'] = indi_nri['STCOFIPS']

In [11]:
kan_nri.head(1)

,OID_,NRI_ID,STATE,STATEABBRV,STATEFIPS,COUNTY,COUNTYTYPE,COUNTYFIPS,STCOFIPS,TRACT,...,WNTW_EALR,WNTW_ALRB,WNTW_ALRP,WNTW_ALRA,WNTW_ALR_NPCTL,WNTW_RISKV,WNTW_RISKS,WNTW_RISKR,NRI_VER,STCNTY
29866,30746,T20001952600,Kansas,KS,20,Allen,County,1,20001,952600,...,Relatively High,0.000013,4.104483e-07,9.270264e-07,83.120337,21079.537153,92.02307,Relatively High,December 2025,20001

**Checking and Handling Missing Data**

In [17]:
#checking for missing values
kan_nri = pd.read_csv("Kansas.csv", low_memory = True)
kan_nri = pd.DataFrame(kan_nri)

indi_nri = pd.read_csv("Indiana.csv", low_memory = True)
indi_nri = pd.DataFrame(indi_nri)

print(kan_nri.isna())

        ST  STATE  ST_ABBR  STCNTY  COUNTY   FIPS  LOCATION  AREA_SQMI  \
0    False  False    False   False   False  False     False      False
1    False  False    False   False   False  False     False      False
2    False  False    False   False   False  False     False      False
3    False  False    False   False   False  False     False      False
4    False  False    False   False   False  False     False      False
..     ...    ...      ...     ...     ...    ...       ...        ...
824  False  False    False   False   False  False     False      False
825  False  False    False   False   False  False     False      False
826  False  False    False   False   False  False     False      False
827  False  False    False   False   False  False     False      False
828  False  False    False   False   False  False     False      False

     E_TOTPOP  M_TOTPOP  ...  EP_ASIAN  MP_ASIAN  EP_AIAN  MP_AIAN  EP_NHPI  \
0       False     False  ...     False     False    False    False    False
1       False     False  ...     False     False    False    False    False
2       False     False  ...     False     False    False    False    False
3       False     False  ...     False     False    False    False    False
4       False     False  ...     False     False    False    False    False
..        ...       ...  ...       ...       ...      ...      ...      ...
824     False     False  ...     False     False    False    False    False
825     False     False  ...     False     False    False    False    False
826     False     False  ...     False     False    False    False    False
827     False     False  ...     False     False    False    False    False
828     False     False  ...     False     False    False    False    False

     MP_NHPI  EP_TWOMORE  MP_TWOMORE  EP_OTHERRACE  MP_OTHERRACE
0      False       False       False         False         False
1      False       False       False         False         False
2      False       False       False         False         False
3      False       False       False         False         False
4      False       False       False         False         False
..       ...         ...         ...           ...           ...
824    False       False       False         False         False
825    False       False       False         False         False
826    False       False       False         False         False
827    False       False       False         False         False
828    False       False       False         False         False

[829 rows x 158 columns]

In [19]:
#dealing with missing values with imputation using the mean
indi_nri_fill_min = indi_nri.fillna(indi_nri.mean(numeric_only=True))
kan_nri_fill_min = kan_nri.fillna(kan_nri.mean(numeric_only=True))